site_name: DFR Technical Wiki
site_url: https://dallasformularacing.wiki.com/

repo_name: DallasFormulaRacing/
repo_url: https://github.com/DallasFormulaRacing/

docs_dir: wiki-site/docs

copyright: Copyright &copy; 2023 - 2024 Dallas Formula Racing

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select

  logo: assets/resized-Cropped-white-logo-DFR.png
  favicon: assets/cropped-Logo-Updated-PNG-1.webp

  
  
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  
  icon:
    admonition:
      note: material/pencil
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/speedometer
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

    repo: fontawesome/brands/github 
    
  
markdown_extensions:
  # Admonitions (Call-outs)
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Annotations, Buttons, Grids, and Images
  - attr_list
  - md_in_html

  # Code Blocks. Content Tabs, and Toolti[s]
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Tables
  - tables

  # Mermaid Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Footnotes
  - footnotes

  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Icons and emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Math via Katex
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

plugins:
  - search
  - glightbox
  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/DallasFormulaRacing
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/dallas-formula-racing
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/dallasformularacing/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dallasformularacing
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/dallasformula
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@dallasformularacing3979

nav:
  - Home: index.md

  - Embedded:
    - Embedded/index.md
    - Getting Started:
      - Embedded/Getting Started/index.md
    - Data Acquisition: 
      - Embedded/Data Acquisition/index.md
      - Developer's Guide:
        - Embedded/Data Acquisition/Dev Guide/index.md
        - Code Editors: Embedded/Data Acquisition/Dev Guide/code-editors.md
        - Build, Flash, and Debug: Embedded/Data Acquisition/Dev Guide/build-flash-debug.md
        - Viewing Serial Output: Embedded/Data Acquisition/Dev Guide/view-serial-output.md
        - Viewing RTOS Threads, Queues, and Memory: Embedded/Data Acquisition/Dev Guide/view-threads-queues-memory.md
        - Unit Testing: Embedded/Data Acquisition/Dev Guide/unit-testing.md
        - Source Code Docs: Embedded/Data Acquisition/Dev Guide/source-code-docs.md
        - Contributing and Version Control: Embedded/Data Acquisition/Dev Guide/contributing-version-control.md
        - Style Guide: Embedded/Data Acquisition/Dev Guide/style-guide.md
        - Code Generator Configs: Embedded/Data Acquisition/Dev Guide/code-generator-configs.md
        - Enabling printf: Embedded/Data Acquisition/Dev Guide/enabling-printf.md
        - Enabling C++: Embedded/Data Acquisition/Dev Guide/enabling-cpp.md
      - Firmware Design:
        - Embedded/Data Acquisition/Firmware Design/index.md
        - Architecture Overview: Embedded/Data Acquisition/Firmware Design/architecture-overview.md
        - File Structure: Embedded/Data Acquisition/Firmware Design/file-structure.md
        - Timing and Concurrency: Embedded/Data Acquisition/Firmware Design/timing-and-concurrency.md    
      - Data Logging:
        - Embedded/Data Acquisition/Application/Data Logger/data_payload.md
        - Embedded/Data Acquisition/Application/Data Logger/circular_queue.md
        - Embedded/Data Acquisition/Application/Data Logger/data_logger.md
        - Embedded/Data Acquisition/Application/RTOS Components/mutex.md
      - File System:
        - Embedded/Data Acquisition/Application/File System/index.md
        - Embedded/Data Acquisition/Application/File System/fat_fs.md
      - Engine Controll Unit (ECU):
        - Embedded/Data Acquisition/Sensor/ECU/index.md
        - Embedded/Data Acquisition/Sensor/ECU/pe3.md
      - Suspension Travel Potentiometers:
        - Embedded/Data Acquisition/Sensor/Linear Potentiometer/index.md
        - Embedded/Data Acquisition/Sensor/Linear Potentiometer/SLS_1322-3.md
      - Accelerometer:
        - Embedded/Data Acquisition/Sensor/Accelerometer/index.md
        - Embedded/Data Acquisition/Sensor/Accelerometer/lsm303dlhc.md
      - Gyroscope:
        - Embedded/Data Acquisition/Sensor/Gyroscope/index.md
        - Embedded/Data Acquisition/Sensor/Gyroscope/l3gd20h.md
      - Supported Platforms:
        - Embedded/Data Acquisition/Supported Platforms/index.md
        - Embedded/Data Acquisition/Supported Platforms/STMicroelectronics/stmicroelectronics.md

    - Dashboard Display:
      - Embedded/Dashboard Display/index.md
      - Developer's Guide:
        - Embedded/Dashboard Display/Dev Guide/index.md
        - Embedded/Dashboard Display/Dev Guide/os-flashing-tools.md
        - Embedded/Dashboard Display/Dev Guide/starter-package.md
        - Embedded/Dashboard Display/Dev Guide/terminal-and-serial.md
        - Embedded/Dashboard Display/Dev Guide/developer-package.md
        - Embedded/Dashboard Display/Dev Guide/running-qt5-apps.md
  
  - Electrical:
      - Electrical/index.md
      - Getting Started:
        - Electrical/Getting Started/index.md
        - Installing KiCAD: Electrical/Getting Started/Installing KiCAD.md
        - KiCAD Learning Project: Electrical/Getting Started/KiCAD Learning Project.md
      - Wire Harness:
        - Electrical/Wire Harness/index.md
      - Custom DAQ PCB Boards:
        - Electrical/Custom DAQ PCB Boards/index.md
        - Electrical/Custom DAQ PCB Boards/DAQ Revision 1/Revision 1.md
      - Sensors:
        - Electrical/Sensors/index.md


  - Software:
    - Software/index.md
  
  - Powertrain:
    - Powertrain/index.md
    - Getting Started:
      - Powertrain/Getting Started/index.md
    - Intake:
      - Powertrain/Intake/index.md
    - Fuel System:
      - Powertrain/Fuel System/index.md
    - Exhaust:
      - Powertrain/Exhaust/index.md
    - Cooling System:
      - Powertrain/Cooling System/index.md
    - Diff Mounting Final Drive:
      - Powertrain/Diff Mounting Final Drive/index.md
    - Drexler:
      - Powertrain/Drexler/index.md

  - Suspension:
    - Suspension/index.md
  
  - Ergonomics:
    - Ergonomics/index.md

  - Manufacturing:
    - Manufacturing/index.md

  - Aerodynamics:
    - Aerodynamics/index.md

  - Chassis:
    - Chassis/index.md
  
  